export declare const serverEnv: {
    NODE_ENV: string;
    API_GATEWAY_PORT: string;
    SERVICE_SYSTEM_PORT: string;
    SERVICE_STUDY_PORT: string;
    SERVICE_AI_PORT: string;
    GATEWAY_API_KEY: string;
    SERVICE_SYSTEM_URL: string;
    SERVICE_STUDY_URL: string;
    SERVICE_AI_URL: string;
    PGHOST: string;
    PGUSER: string;
    PGPASSWORD: string;
    PGPORT: string;
    INIT_SCHEMA: string;
    EMAIL_HOST: string;
    EMAIL_PORT: string;
    EMAIL_SECURE: string;
    EMAIL_USER: string;
    EMAIL_PASSWORD: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GOOGLE_REDIRECT_URI: string;
    SESSION_SECRET: string;
    MEMCACHE_URL: string;
};
//# sourceMappingURL=env.d.ts.map